const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const person = fs.readFileSync(path.join(root, 'packages/school/MVC/views/school/schedule/personSchedule.ejs'), 'utf8');
const hub = fs.readFileSync(path.join(root, 'packages/school/MVC/views/school/masterAcademiaHub.ejs'), 'utf8');
const controller = fs.readFileSync(path.join(root, 'packages/school/MVC/controllers/school/scheduleController.js'), 'utf8');
test('schedule pages mark report events and mirror day/month switching', () => {
assert.ok(person.includes('report-priority-marker'), 'person schedule has report marker');
assert.ok(person.includes("=== 'report_task'") && hub.includes("=== 'report_task'"), 'report task events are classified');
assert.ok(hub.includes('report-priority-marker'), 'master hub has report marker');
assert.ok(person.includes('bi-stars') && hub.includes('bi-stars'), 'report markers use stars icon');
assert.ok(person.includes('@keyframes reportPriorityBlink') && hub.includes('@keyframes reportPriorityBlink'), 'both views blink report markers');
assert.ok(person.includes('data-schedule-view-vertical') && person.includes('data-schedule-view-timeline') && person.includes('data-schedule-view-month'), 'person schedule has vertical/horizontal/month switches');
assert.ok(person.includes("viewMode: 'verticalTimeline'"), 'person schedule defaults to vertical day view');
assert.ok(person.includes("scheduleState.viewMode = verticalButton ? 'verticalTimeline' : (dayButton ? 'timeline' : 'calendar')"), 'person schedule toggles view mode');
assert.ok(person.includes('function renderVerticalTimelineView'), 'person schedule renders vertical day columns');
assert.ok(person.includes('id="scheduleShortcutsModal"') && person.includes('id="scheduleLegendModal"'), 'person schedule uses shortcut and legend modals');
assert.ok(person.includes('schoolMasterViewer.scheduleDayWidth'), 'person schedule persists day width');
assert.ok(person.includes('scheduleState = {') && person.includes('id="schedulePersonTabs"') && person.includes('btn_loadAllSchedules'), 'person schedule supports multi-person tabs and bulk load');
assert.ok(person.indexOf('for="sch_role"') < person.indexOf('id="btn_openPersonPicker"'), 'person schedule places role before select people');
assert.ok(person.includes('<option value="teacher" selected>Teacher</option>'), 'person schedule defaults admin role to teacher');
assert.ok(person.includes("pickerParams.set('role', pickerRole)") && person.includes('apiEndpoint: pickerEndpoint'), 'person picker endpoint includes selected role filtering');
assert.ok(person.includes('function scheduleStatusChip') && person.includes('function buildScheduleEventTooltip'), 'person schedule uses hub-style card status and tooltip helpers');
assert.ok(person.includes("return detailParts.join('\\n')") && person.includes('sch-tip-date'), 'person schedule tooltip renders newline field rows with LTR dates');
assert.ok(person.includes('schedule-status-chip') && person.includes('schedule-event-title') && !person.includes('Open item details'), 'person schedule cards use status chip and avoid old open-details tooltip text');
assert.ok(person.includes('function scheduleSoloStudentHtml') && person.includes('schedule-event-student') && person.includes("addDetail('Student', event?.soloStudentName || event?.singleStudentName)"), 'person schedule displays one-to-one student names on session cards and tooltips');
assert.ok(hub.includes('function hubScheduleSoloStudentHtml') && hub.includes('hub-schedule-event-student') && hub.includes("addDetail('Student', event?.soloStudentName || event?.singleStudentName)"), 'master hub displays one-to-one student names on session cards and tooltips');
assert.ok(person.includes('selectedSessionKeysByPersonId') && person.includes('function scheduleSessionSelectionKey') && person.includes('data-schedule-session-select'), 'person schedule supports selectable session cards');
assert.ok(hub.includes('selectedSessionKeysByPersonId') && hub.includes('function hubScheduleSessionSelectionKey') && hub.includes('data-hub-schedule-session-select'), 'master hub supports selectable session cards');
assert.ok(person.includes('data-schedule-clear-all-selected') && hub.includes('data-hub-schedule-clear-selected-sessions') && person.includes('is-session-selected') && hub.includes('is-session-selected'), 'schedule pages show selected-session count and selected card styling');
assert.ok(person.includes('function activeScheduleSelectedClassId') && person.includes('function canSelectScheduleSession') && person.includes('bi-check-lg') && person.includes('bi-x-lg'), 'person schedule limits selected sessions to one class with check/cross selectors');
assert.ok(hub.includes('function activeHubScheduleSelectedClassId') && hub.includes('function canSelectHubScheduleSession') && hub.includes('bi-check-lg') && hub.includes('bi-x-lg'), 'master hub limits selected sessions to one class with check/cross selectors');
assert.ok(person.includes('schedule-selected-count-pill') && hub.includes('hub-schedule-selected-count-pill'), 'schedule pages use enhanced selected-count pill styling');
assert.ok(person.includes('!(selectedClassId && card)') && person.includes("card?.getAttribute('data-schedule-session-key')"), 'person schedule allows whole-card selection only after selection mode starts');
assert.ok(hub.includes('!(selectedClassId && card)') && hub.includes("card?.getAttribute('data-hub-schedule-session-key')"), 'master hub allows whole-card selection only after selection mode starts');
assert.ok(person.includes('class="schedule-visual-area"') && person.includes('max-height: none') && !person.includes('style="max-height: 800px; overflow-y: auto;"'), 'person schedule visual area avoids fixed vertical scroll box');
assert.ok(person.includes('window.showLoading(`Loading schedule for ${person.name || person.id}...`)') && person.includes('window.hideLoading({ force: true })'), 'person schedule shows loading modal with active person name');
assert.ok(person.includes("title: ''") && !person.includes("Browse any school person's schedule across daily"), 'person schedule suppresses page title and intro copy');
assert.ok(person.indexOf('id="scheduleTitle"') < person.indexOf('id="scheduleHoursSummary"'), 'person schedule shows hours summary under viewing title');
assert.ok(person.includes('function fetchSchedulePeopleForRole') && person.includes("pageSize: '100'") && person.includes("params.set('role', normalizedRole)"), 'person schedule can fetch all people for a selected role');
assert.ok(person.includes('if (canSelectAnyPerson && selectedScheduleRole())'), 'person schedule load-all expands selected role instead of requiring manual chips');
assert.ok(!person.includes('Total Hours By Category') && !person.includes('schedule-hours-summary-title'), 'person schedule hours summary shows only chips');
assert.ok(!person.includes('Schedule View</div>'), 'person schedule removes extra schedule view header text');
assert.ok(person.includes('const reportMarker = dayEvents.some(isReportScheduleEvent)'), 'person calendar marks report days');
assert.ok(hub.includes('data-hub-schedule-view-timeline') && hub.includes('data-hub-schedule-view-month'), 'master hub has day/month switches');
assert.ok(hub.includes('const reportMarker = reportEvent ? buildReportPriorityMarker(reportEvent) :'), 'master hub marks report days');
assert.ok(controller.includes('const roleFilter = normalizeScheduleRole(req.query.role)'), 'schedule picker reads role query');
assert.ok(controller.includes('row.roles.map(normalizeScheduleRole).includes(roleFilter)'), 'schedule picker filters rows by normalized role');
assert.ok(controller.includes('items,') && controller.includes('data: items') && controller.includes('results: items'), 'schedule picker response shape remains compatible');
assert.ok(controller.includes('function buildSoloStudentResolver') && controller.includes('getClassScheduleCapacity(classRow) !== 1'), 'schedule controller resolves one-to-one class sessions by capacity');
assert.ok(controller.includes('soloStudentName: soloStudent?.soloStudentName ||') && controller.includes('singleStudentName: soloStudent?.soloStudentName ||'), 'schedule events expose one-to-one student name fields');
});
