const coreContracts = require('./pteCoreContracts');

module.exports = {
  adminChekersService: coreContracts.adminChekersService,
  activityQuotaLedgerService: coreContracts.activityQuotaLedgerService,
  coreFilesService: coreContracts.coreFilesService,
  uploadCategoryResolverService: coreContracts.uploadCategoryResolverService,
  uploadFolderSettingsService: coreContracts.uploadFolderSettingsService,
  settingService: coreContracts.settingService,
  dataService: coreContracts.dataService,
  normalizeQueryOptions: coreContracts.normalizeQueryOptions,
  resolveEntity: coreContracts.resolveEntity,
  applyGenericFilter: coreContracts.applyGenericFilter,
  getActiveOrgIdOrThrow: coreContracts.getActiveOrgIdOrThrow,
  idsEqual: coreContracts.idsEqual,
  toPublicId: coreContracts.toPublicId,
  paginate: coreContracts.paginate,
  buildDataServiceQuery: coreContracts.buildDataServiceQuery,
  inferSearchableFields: coreContracts.inferSearchableFields,
  isAjax: coreContracts.isAjax,
  isRailwayProxyMode: coreContracts.isRailwayProxyMode,
  getGatewayBaseUrl: coreContracts.getGatewayBaseUrl,
  getGatewayTimeoutMs: coreContracts.getGatewayTimeoutMs,
  assertCreateOrgContextOrThrow: coreContracts.assertCreateOrgContextOrThrow,
  normalizeOrgRoles: coreContracts.normalizeOrgRoles,
  decrypt: coreContracts.decrypt,
  runByRepositoryBackend: coreContracts.runByRepositoryBackend,
  getMongoCollection: coreContracts.getMongoCollection,
  SYSTEM_CONTEXT: coreContracts.SYSTEM_CONTEXT,
  SECTIONS: coreContracts.SECTIONS,
  OPERATIONS: coreContracts.OPERATIONS
};
