const { SECTIONS: CORE_SECTIONS, OPERATIONS } = require('../../../config/accessConstants');

const PTE_SECTIONS = Object.freeze({
  PTE: 'PTE',
  PTE_PUBLIC_PAGE: 'PTE_PUBLIC_PAGE',
  PTE_PEOPLE: 'PTE_PEOPLE',
  PTE_STUDENTS: 'PTE_STUDENTS',
  PTE_PUBLIC_APPLICANTS: 'PTE_PUBLIC_APPLICANTS',
  PTE_TEACHERS: 'PTE_TEACHERS',
  PTE_QUESTIONS_BANK: 'PTE_QUESTIONS_BANK',
  PTE_TESTS: 'PTE_TESTS',
  PTE_COURSES: 'PTE_COURSES',
  PTE_AI_ASSISST: 'PTE_AI_ASSISST',
  PTE_AI_PROVIDER_KEYS: 'PTE_AI_PROVIDER_KEYS',
  PTE_AI_SCORING_SETTINGS: 'PTE_AI_SCORING_SETTINGS',
  PTE_AI_TOKEN_USAGE: 'PTE_AI_TOKEN_USAGE',
  PTE_SCORING: 'PTE_SCORING',
  PTE_SCORING_DEFAULTS: 'PTE_SCORING_DEFAULTS',
  PTE_ATTEMPT: 'PTE_ATTEMPT',
  PTE_ATTEMPT_LEDGER: 'PTE_ATTEMPT_LEDGER',
  PTE_ATTEMPT_DETAILS: 'PTE_ATTEMPT_DETAILS',
  PTE_ATTEMPT_OVERALL_PERFORMANCE: 'PTE_ATTEMPT_OVERALL_PERFORMANCE',
  PTE_PRACTICE: 'PTE_PRACTICE',
  PTE_PRACTICE_BY_SKILLS: 'PTE_PRACTICE_BY_SKILLS',
  PTE_SMART_PRACTICE: 'PTE_SMART_PRACTICE',
  PTE_MOCK_EXAMS: 'PTE_MOCK_EXAMS',
  PTE_FEEDBACK: 'PTE_FEEDBACK',
  PTE_FEEDBACK_ON_PRACTICE: 'PTE_FEEDBACK_ON_PRACTICE',
  PTE_TOOLS_AND_REPORTS: 'PTE_TOOLS_AND_REPORTS'
});

const SECTIONS = Object.freeze({
  ...(CORE_SECTIONS || {}),
  ...PTE_SECTIONS
});

module.exports = {
  PTE_SECTIONS,
  SECTIONS,
  OPERATIONS
};
