// config/accessConstants.js

/* ============================================================
   SECTION IDENTIFIERS
   (Used in Routes and Database "sectionId")
============================================================ */
const SECTIONS = {
    USERS: 'USERS',
    PERSONS: 'PERSONS',
    ORGANIZATIONS: 'ORGANIZATIONS',
    OPERATIONS: 'OPERATIONS',
    ROLES: 'ROLES',
    SECTIONS: 'SECTIONS',
    SCOPES: 'SCOPES',
    ACCESS_PROFILES: 'ACCESS_PROFILES', 
    ACCESS_POLICIES: 'ACCESS_POLICIES',
    LOGS: 'LOGS',
    TABLE_SETTINGS: 'TABLE_SETTINGS',
    DASHBOARD: 'DASHBOARD',
    ACTION_STATES: 'ACTION_STATES',
    TRACK_ACTIVITY: 'TRACK_ACTIVITY',
    ORGANIZATION_POLICIES: 'ORGANIZATION_POLICIES',
    SYMBOLS: 'SYMBOLS',
    UPLOADED_FILES: 'UPLOADED_FILES',
    TASKS: 'TASKS',
    CONTACT_MESSAGES: 'CONTACT_MESSAGES',
    NEWSLETTERS: 'NEWSLETTERS',
    SUBSCRIPTION_GROUPS: 'SUBSCRIPTION_GROUPS',
    CHATS: 'CHATS',
    USER_MEMBERSHIPS: 'USER_MEMBERSHIPS',
    HELP: 'HELP',
    SYSTEM_SETTINGS: 'SYSTEM_SETTINGS',
    SYSTEM_UPLOAD_FOLDERS: 'SYSTEM_UPLOAD_FOLDERS',
    WEBSITE_POLICY: 'WEBSITE_POLICY',
    DEBUG_HUB: 'DEBUG_HUB',
    DEBUG_ACCESS_SIMULATOR: 'DEBUG_ACCESS_SIMULATOR',
    DEBUG_ACCESS_AUDITOR: 'DEBUG_ACCESS_AUDITOR',
    DEBUG_INTEGRITY_AUDITOR: 'DEBUG_INTEGRITY_AUDITOR',
    DEBUG_USER_PERSON_CHECKER: 'DEBUG_USER_PERSON_CHECKER',
    DEBUG_USER_SESSION_INSPECTOR: 'DEBUG_USER_SESSION_INSPECTOR',
    DEBUG_HEIC_CONVERTER: 'DEBUG_HEIC_CONVERTER',
    EMAIL_MANAGEMENT: 'EMAIL_MANAGEMENT',
    EMAIL_TEMPLATES: 'EMAIL_TEMPLATES',
    EMAIL_LEDGER: 'EMAIL_LEDGER',
    //
    SCHOOL: 'SCHOOL',
    SCHOOL_DASHBOARD: 'SCHOOL',
    SCHOOL_STUDENTS: 'SCHOOL_STUDENTS',
    SCHOOL_TEACHERS: 'SCHOOL_TEACHERS',
    SCHOOL_STAFF: 'SCHOOL_STAFF',
    SCHOOL_SUBJECTS: 'SCHOOL_SUBJECTS',
    SCHOOL_TERMS: 'SCHOOL_TERMS',
    SCHOOL_CLASSES: 'SCHOOL_CLASSES',
    SCHOOL_CLASS_ENROLLMENT_PERIODS: 'SCHOOL_CLASS_ENROLLMENT_PERIODS',
    SCHOOL_CLASS_CYCLES: 'SCHOOL_CLASS_CYCLES',
    SCHOOL_DEPARTMENTS: 'SCHOOL_DEPARTMENTS',
    SCHOOL_PAY_RATES: 'SCHOOL_PAY_RATES',
    SCHOOL_SESSION_STATUSES: 'SCHOOL_SESSION_STATUSES',
    SCHOOL_TIMESHEET_PERIODS: 'SCHOOL_TIMESHEET_PERIODS',
    SCHOOL_TIMESHEETS: 'SCHOOL_TIMESHEETS',
    SCHOOL_SCHEDULES: 'SCHOOL_SCHEDULES',
    SCHOOL_SESSIONS: 'SCHOOL_SESSIONS',
    SCHOOL_REPORTS: 'SCHOOL_REPORTS',
    SCHOOL_REPORTS_TEMPLATE: 'SCHOOL_REPORTS_TEMPLATE',
    SCHOOL_REPORTS_ASSIGNMENT: 'SCHOOL_REPORTS_ASSIGNMENT',
    SCHOOL_REPORTS_INSTANCES: 'SCHOOL_REPORTS_INSTANCES',
    /** @deprecated Legacy monolithic exam section; kept for old policies until migrated */
    SCHOOL_EXAMS: 'SCHOOL_EXAMS',
    SCHOOL_EXAMS_TEMPLATE: 'SCHOOL_EXAMS_TEMPLATE',
    SCHOOL_EXAMS_ALLOCATION: 'SCHOOL_EXAMS_ALLOCATION',
    SCHOOL_EXAMS_TAKING: 'SCHOOL_EXAMS_TAKING',
    SCHOOL_EXAMS_REVIEW: 'SCHOOL_EXAMS_REVIEW',
    
    SCHOOL_ATTENDANCES: 'SCHOOL_ATTENDANCES',
    SCHOOL_GRADEBOOK: 'SCHOOL_GRADEBOOK',
    SCHOOL_HOLIDAYS: 'SCHOOL_HOLIDAYS',
    SCHOOL_PROGRAMS: 'SCHOOL_PROGRAMS',
    SCHOOL_PROGRAM_REGISTRATIONS: 'SCHOOL_PROGRAM_REGISTRATIONS',
    SCHOOL_TERM_REGISTRATIONS: 'SCHOOL_TERM_REGISTRATIONS',
    // Canonical section id (renamed from legacy SCHOOL_FEE_DEFINITIONS)
    SCHOOL_TRANSACTION_TEMPLATES: 'SCHOOL_TRANSACTION_TEMPLATES',
    // Backward-compatible aliases
    SCHOOL_TRANSACTION_DEFINITIONS: 'SCHOOL_TRANSACTION_TEMPLATES',
    SCHOOL_FEE_DEFINITIONS: 'SCHOOL_TRANSACTION_TEMPLATES',
    SCHOOL_ACCOUNTS: 'SCHOOL_ACCOUNTS',
    SCHOOL_TRANSACTIONS: 'SCHOOL_TRANSACTIONS',
    SCHOOL_SAMPLE_DATA: 'SCHOOL_SAMPLE_DATA',
    SCHOOL_ACADEMIC_LEDGER: 'SCHOOL_ACADEMIC_LEDGER',
    SCHOOL_WITHDRAWAL: 'SCHOOL_WITHDRAWAL',
    //
    ACTIVITY_QUOTA: 'ACTIVITY_QUOTA',
    ACTIVITY_QUOTA_OVERVIEW: 'ACTIVITY_QUOTA_OVERVIEW',
    ACTIVITY_QUOTA_CREDIT_CHECK: 'ACTIVITY_QUOTA_CREDIT_CHECK',
    ACTIVITY_QUOTA_LEDGER: 'ACTIVITY_QUOTA_LEDGER',
    ACTIVITY_QUOTA_RULES: 'ACTIVITY_QUOTA_RULES',
    ACTIVITY_QUOTA_ADD_CREDIT: 'ACTIVITY_QUOTA_ADD_CREDIT',
    ACTIVITY_QUOTA_PACKAGE: 'ACTIVITY_QUOTA_PACKAGE',
    ACTIVITY_QUOTA_PACKAGE_MANAGER: 'ACTIVITY_QUOTA_PACKAGE_MANAGER',
    //
    PTE: 'PTE',
    PTE_PUBLIC_PAGE: 'PTE_PUBLIC_PAGE',
    PTE_PEOPLE: 'PTE_PEOPLE',
    PTE_STUDENTS: 'PTE_STUDENTS',
    PTE_PUBLIC_APPLICANTS: 'PTE_PUBLIC_APPLICANTS',
    PTE_TEACHERS: 'PTE_TEACHERS',
    PTE_QUESTIONS_BANK: 'PTE_QUESTIONS_BANK',
    PTE_TESTS: 'PTE_TESTS',
    PTE_COURSES: 'PTE_COURSES',
    PTE_AI_ASSISST: 'PTE_AI_ASSISST',
    PTE_AI_PROVIDER_KEYS: 'PTE_AI_PROVIDER_KEYS',
    PTE_AI_SCORING_SETTINGS: 'PTE_AI_SCORING_SETTINGS',
    PTE_AI_TOKEN_USAGE: 'PTE_AI_TOKEN_USAGE',
    PTE_SCORING: 'PTE_SCORING',
    PTE_SCORING_DEFAULTS: 'PTE_SCORING_DEFAULTS',
    PTE_ATTEMPT: 'PTE_ATTEMPT',
    PTE_ATTEMPT_LEDGER: 'PTE_ATTEMPT_LEDGER',
    PTE_ATTEMPT_DETAILS: 'PTE_ATTEMPT_DETAILS',
    PTE_ATTEMPT_OVERALL_PERFORMANCE: 'PTE_ATTEMPT_OVERALL_PERFORMANCE',
    PTE_PRACTICE: 'PTE_PRACTICE',
    PTE_PRACTICE_BY_SKILLS: 'PTE_PRACTICE_BY_SKILLS',
    PTE_SMART_PRACTICE: 'PTE_SMART_PRACTICE',
    PTE_MOCK_EXAMS: 'PTE_MOCK_EXAMS',
    PTE_FEEDBACK: 'PTE_FEEDBACK',
    PTE_FEEDBACK_ON_PRACTICE: 'PTE_FEEDBACK_ON_PRACTICE',
    //
    IELTS: 'IELTS',
    IELTS_DASHBOARD: 'IELTS',
    IELTS_SCORING_PIPELINES: 'IELTS_SCORING_PIPELINES',
    IELTS_SCORING_HISTORY: 'IELTS_SCORING_HISTORY',
    IELTS_API_PROVIDERS: 'IELTS_API_PROVIDERS',
    IELTS_AI_TOKEN_USAGE: 'IELTS_AI_TOKEN_USAGE',
    //
    BENCHPATH: 'BENCHPATH',
    BENCHPATH_DASHBOARD: 'BENCHPATH',
    BENCHPATH_SOURCES: 'BENCHPATH_SOURCES',
    BENCHPATH_SOURCE_FRAGMENTS: 'BENCHPATH_SOURCE_FRAGMENTS',
    BENCHPATH_CLB_FRAMEWORK: 'BENCHPATH_CLB_FRAMEWORK',
    BENCHPATH_CLB_STAGES: 'BENCHPATH_CLB_STAGES',
    BENCHPATH_CLB_SKILLS: 'BENCHPATH_CLB_SKILLS',
    BENCHPATH_CLB_COMPETENCY_AREAS: 'BENCHPATH_CLB_COMPETENCY_AREAS',
    BENCHPATH_CLB_BENCHMARKS: 'BENCHPATH_CLB_BENCHMARKS',
    BENCHPATH_CLB_COMPETENCIES: 'BENCHPATH_CLB_COMPETENCIES',
    BENCHPATH_CLB_INDICATORS: 'BENCHPATH_CLB_INDICATORS',
    BENCHPATH_CLB_PROFILE_OF_ABILITY: 'BENCHPATH_CLB_PROFILE_OF_ABILITY',
    BENCHPATH_CLB_FEATURES_OF_COMMUNICATION: 'BENCHPATH_CLB_FEATURES_OF_COMMUNICATION',
    BENCHPATH_CLB_SAMPLE_TASK_LABELS: 'BENCHPATH_CLB_SAMPLE_TASK_LABELS',
    BENCHPATH_TASK_AUTHORING: 'BENCHPATH_TASK_AUTHORING'
    
};

/* ============================================================
   GENERIC OPERATION IDENTIFIERS
   (Reused across all sections)
============================================================ */
const OPERATIONS = {
    // Standard CRUD
    READ: 'READ',      // View list or details
    READ_ALL: 'READ_ALL',      // View list or details
    CREATE: 'CREATE',  // Add new item
    UPDATE: 'UPDATE',  // Edit existing item
    CONFIGURE: 'CONFIGURE', // Configure settings/state
    DELETE: 'DELETE',  // Remove item
    DELETE_ALL: 'DELETE_ALL',  // Remove item

    // Extended Actions
    START: 'START', // Start a process/session
    SAVE: 'SAVE', // Save progress/state
    EXPORT: 'EXPORT',  // Export data (CSV/JSON)
    IMPORT: 'IMPORT',  // Bulk import
    DOWNLOAD_FILE: 'DOWNLOAD_FILE',
    DELETE_FILE: 'DELETE_FILE',
    AI_SCORING: 'AI_SCORING', // Run AI scoring/feedback workflows
    // Specific / Utility
    UNLINK: 'UNLINK',  // e.g. Unlink User from Person
    CLEAR_ALL: 'CLEAR_ALL', // e.g. Clear all logs
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',
    //Operation to check if a personID linked to a user account.
    USERS_CHECK_LINKEDPERSON: 'USERS_CHECK_LINKEDPERSON',
    LOGS: 'LOGS'
};

module.exports = {
    SECTIONS,
    OPERATIONS
};
